export type Locale = "pt" | "en";

type RealmKey = "hanamori" | "mizukyo" | "kurogane";

export const immersiveCopy = {
  pt: {
    languageLabel: "Idioma",
    enter: {
      overline: "月の原 · ECLIPSE OF THE NINE REALMS",
      line: "A lua esqueceu. Mas você lembra.",
      withSound: "Entrar com som",
      silent: "Entrar em silêncio",
    },
    nav: {
      threshold: "Limiar",
      realms: "Reinos",
      akari: "Akari",
      lore: "Memórias",
      eclipse: "Eclipse",
      menu: "Menu",
      close: "Fechar",
      sound: "Som",
    },
    navJp: {
      threshold: "境界",
      realms: "九国",
      akari: "朱莉",
      lore: "記憶",
      eclipse: "月蝕",
    },
    hero: {
      eyebrow: "ECLIPSE OF THE NINE REALMS",
      title: "Quando a lua esquecer o mundo, quem lembrará de nós?",
      titleJp: "月が世界を忘れたとき、誰が私たちを覚えているのか。",
      body: "A Lua-Mãe guardava as memórias dos vivos, dos mortos, dos espíritos e dos deuses. Agora ela está se partindo. Vilas desaparecem, templos perdem seus nomes e criaturas nascidas do esquecimento atravessam os Nove Reinos.",
      cue: "Siga a memória",
      vertical: "忘却ノ月",
    },
    threshold: {
      label: "01 — KINTSUGI LUNAR",
      title: "O que foi apagado ainda pode voltar — por alguns instantes.",
      titleJp: "忘れられたものは、月光で再び形を得る。",
      body: "Com sua máscara kitsune, Akari enxerga fragmentos esquecidos da realidade. Kintsugi Lunar permite restaurar pontes quebradas, plataformas, portas, mecanismos e caminhos que a própria lua apagou. A pergunta nunca é apenas onde seguir — mas o que vale a pena trazer de volta.",
      cta: "Restaurar o caminho",
      stats: [
        ["09", "reinos sob o eclipse"],
        ["01", "lua que está esquecendo"],
        ["02", "guardiões ao seu lado"],
        ["∞", "memórias esperando retorno"],
      ],
    },
    realmsIntro: {
      label: "02 — OS NOVE REINOS",
      title: "Cada reino está desaparecendo de uma forma diferente.",
      titleJp: "九つの国、それぞれに異なる忘却。",
      body: "O overworld de Tsukihara é um diorama vivo de templos, vilas, pontes, ruínas e caminhos perdidos. A progressão do eclipse transforma regiões inteiras, abre rotas e apaga outras — e cada entrada leva a uma fase 2.5D de exploração, combate, puzzles e backtracking.",
    },
    realms: {
      hanamori: {
        label: "Reino das Cerejeiras",
        copy: "Hanamori é o primeiro rosto de Tsukihara: sakuras, pontes vermelhas, rios, vilarejos e santuários que ainda parecem acolhedores. A corrupção lunar surge primeiro como detalhe — uma lanterna sem nome, uma trilha que ninguém lembra, uma ponte que desapareceu da história.",
      },
      mizukyo: {
        label: "Reino dos Espelhos d’Água",
        copy: "Mizukyo é feito de lagos, cachoeiras e templos submersos. Reflexos escondem rotas e ameaças, enquanto memórias restauradas transformam água, altura e ilusão em ferramentas de exploração.",
      },
      kurogane: {
        label: "Reino do Ferro Negro",
        copy: "Kurogane mistura fábricas antigas, forjas, templos metálicos e máquinas sagradas que continuam rezando para deuses quebrados. É onde tecnologia espiritual e esquecimento se tornam parte da mesma ruína.",
      },
    } satisfies Record<RealmKey, { label: string; copy: string }>,
    trailer: {
      label: "03 — VISLUMBRE DO COMBATE",
      title: "Uma dança de lâmina, pétalas e luz lunar.",
      titleJp: "刃と花びらと月光の舞。",
      body: "Tsukihara combina combate lateral elegante, mobilidade rápida, habilidades de travessia e encontros que mudam conforme Akari recupera fragmentos do mundo. Cada golpe precisa parecer preciso; cada movimento, parte de uma dança.",
    },
    akari: {
      eyebrow: "04 — AKARI NO REI · 朱莉",
      title: "Todos parecem lembrar do que Akari fez. Ela não lembra de nada.",
      titleJp: "皆は朱莉の罪を覚えている。彼女だけが何も覚えていない。",
      body: "Akari desperta sem memórias, carregando uma máscara kitsune, uma katana e uma culpa que o mundo inteiro parece reconhecer. Ao lado de Haku e Mochi, ela atravessa os reinos tentando descobrir se foi vítima, heroína ou a causa do Eclipse Carmesim.",
      specs: ["Arma — Katana", "Dom — Kintsugi Lunar", "Companheiros — Haku / Mochi"],
    },
    lore: {
      label: "05 — MEMÓRIAS FRATURADAS",
      title: "A lua não está morrendo. Ela está esquecendo.",
      titleJp: "月は死んでいるのではない。忘れている。",
      intro: "Quanto mais realidade Akari restaura, mais a história de Tsukihara deixa de parecer uma lenda — e mais próxima ela chega da verdade que foi apagada dela.",
      items: [
        ["01", "Lua-Mãe", "月母", "A entidade divina que preservava as memórias de vivos, mortos, espíritos e deuses começou a esquecer aquilo que jurou guardar."],
        ["02", "Kintsugi Lunar", "月継", "Akari escolhe quais fragmentos esquecidos restaurar e quando sustentá-los com luz lunar — na exploração, em puzzles e durante o combate."],
        ["03", "Haku e Mochi", "守護", "Haku abre possibilidades de travessia e poder lunar. Mochi percebe segredos, paredes falsas e memórias escondidas onde ninguém mais enxerga nada."],
        ["04", "Vazios Lunares", "虚月", "Quando uma memória desaparece por completo, alguma coisa ocupa o espaço que ela deixou. Nem toda ausência permanece vazia."],
        ["05", "Eclipse Carmesim", "紅蝕", "Não é apenas um fenômeno no céu. O eclipse muda o mapa, corrompe regiões, acorda máquinas e aproxima Akari da origem do esquecimento."],
      ],
    },
    eclipse: {
      label: "06 — O ECLIPSE CARMESIM",
      title: "A lua esqueceu. Mas você lembra.",
      titleJp: "月は忘れた。それでも、あなたは覚えている。",
      body: "Atravesse um overworld isométrico vivo, entre em fases Metroidvania 2.5D, recupere habilidades, restaure fragmentos da realidade e enfrente os seres que prosperam onde a memória desaparece. O destino dos Nove Reinos começa com aquilo que Akari conseguir lembrar.",
      return: "Voltar ao início da memória",
      development: "Em desenvolvimento",
    },
  },
  en: {
    languageLabel: "Language",
    enter: {
      overline: "月の原 · ECLIPSE OF THE NINE REALMS",
      line: "The moon forgot. But you remember.",
      withSound: "Enter with sound",
      silent: "Enter in silence",
    },
    nav: {
      threshold: "Kintsugi",
      realms: "Realms",
      akari: "Akari",
      lore: "Memories",
      eclipse: "Eclipse",
      menu: "Menu",
      close: "Close",
      sound: "Sound",
    },
    navJp: {
      threshold: "境界",
      realms: "九国",
      akari: "朱莉",
      lore: "記憶",
      eclipse: "月蝕",
    },
    hero: {
      eyebrow: "ECLIPSE OF THE NINE REALMS",
      title: "When the moon forgets the world, who will remember us?",
      titleJp: "月が世界を忘れたとき、誰が私たちを覚えているのか。",
      body: "The Mother Moon once held the memories of the living, the dead, spirits and gods. Now it is breaking apart. Villages vanish, temples lose their names, and creatures born from oblivion cross the Nine Realms.",
      cue: "Follow the memory",
      vertical: "忘却ノ月",
    },
    threshold: {
      label: "01 — LUNAR KINTSUGI",
      title: "What was erased can return — for a little while.",
      titleJp: "忘れられたものは、月光で再び形を得る。",
      body: "Through her kitsune mask, Akari can see fragments of reality that the moon has forgotten. Lunar Kintsugi restores broken bridges, platforms, doors, mechanisms and paths for a limited time. The question is never only where to go — but what is worth bringing back.",
      cta: "Restore the path",
      stats: [["09", "realms beneath the eclipse"], ["01", "moon that is forgetting"], ["02", "guardians beside you"], ["∞", "memories waiting to return"]],
    },
    realmsIntro: {
      label: "02 — THE NINE REALMS",
      title: "Every realm is being forgotten in a different way.",
      titleJp: "九つの国、それぞれに異なる忘却。",
      body: "Tsukihara's overworld is a living diorama of temples, villages, bridges, ruins and lost paths. The advancing eclipse changes entire regions, reveals routes and erases others — and every entrance leads into a 2.5D stage built around exploration, combat, puzzles and backtracking.",
    },
    realms: {
      hanamori: {
        label: "Realm of Cherry Blossoms",
        copy: "Hanamori is the first face of Tsukihara: sakura, red bridges, rivers, villages and shrines that still feel welcoming. Lunar corruption first appears as a detail — a lantern without a name, a path nobody remembers, a bridge erased from history.",
      },
      mizukyo: {
        label: "Realm of Water Mirrors",
        copy: "Mizukyo is built from lakes, waterfalls and submerged temples. Reflections conceal routes and threats while restored memories turn water, height and illusion into tools for exploration.",
      },
      kurogane: {
        label: "Realm of Black Iron",
        copy: "Kurogane blends old factories, forges, metal shrines and sacred machines that still pray to broken gods. It is where spiritual technology and oblivion become parts of the same ruin.",
      },
    } satisfies Record<RealmKey, { label: string; copy: string }>,
    trailer: {
      label: "03 — A GLIMPSE OF COMBAT",
      title: "A dance of blade, petals and moonlight.",
      titleJp: "刃と花びらと月光の舞。",
      body: "Tsukihara combines elegant side-scrolling combat, fast movement, traversal abilities and encounters that change as Akari restores fragments of the world. Every strike should feel precise; every movement, part of a dance.",
    },
    akari: {
      eyebrow: "04 — AKARI NO REI · 朱莉",
      title: "Everyone remembers what Akari did. She remembers nothing.",
      titleJp: "皆は朱莉の罪を覚えている。彼女だけが何も覚えていない。",
      body: "Akari awakens without memories, carrying a kitsune mask, a katana and a guilt the whole world seems to recognize. With Haku and Mochi beside her, she crosses the realms to discover whether she was a victim, a hero, or the cause of the Crimson Eclipse.",
      specs: ["Weapon — Katana", "Gift — Lunar Kintsugi", "Companions — Haku / Mochi"],
    },
    lore: {
      label: "05 — FRACTURED MEMORIES",
      title: "The moon is not dying. It is forgetting.",
      titleJp: "月は死んでいるのではない。忘れている。",
      intro: "The more reality Akari restores, the less Tsukihara's history feels like legend — and the closer she comes to the truth that was erased from her.",
      items: [
        ["01", "Mother Moon", "月母", "The divine being that preserved the memories of living, dead, spirits and gods has begun to forget what it once swore to keep."],
        ["02", "Lunar Kintsugi", "月継", "Akari chooses which forgotten fragments to restore and when to sustain them with moonlight — across exploration, puzzles and combat."],
        ["03", "Haku and Mochi", "守護", "Haku opens new possibilities for traversal and lunar power. Mochi senses secrets, false walls and hidden memories where nobody else sees anything."],
        ["04", "Lunar Voids", "虚月", "When a memory disappears completely, something takes the space it leaves behind. Not every absence stays empty."],
        ["05", "Crimson Eclipse", "紅蝕", "It is more than a phenomenon in the sky. The eclipse changes the map, corrupts regions, awakens machines and pulls Akari toward the origin of oblivion."],
      ],
    },
    eclipse: {
      label: "06 — THE CRIMSON ECLIPSE",
      title: "The moon forgot. But you remember.",
      titleJp: "月は忘れた。それでも、あなたは覚えている。",
      body: "Cross a living isometric overworld, enter 2.5D Metroidvania stages, recover abilities, restore fragments of reality and confront the beings that thrive where memory disappears. The fate of the Nine Realms begins with what Akari can remember.",
      return: "Return to the first memory",
      development: "In development",
    },
  },
} as const;